import {
  useState,
  type ComponentProps,
  type ReactNode,
} from "react";
import {
  defaultProductFormValues,
  generateSkuFromName,
  toCreateProductInput,
  type ProductFormValues,
  type ProductVariantFormValues,
} from "../adminProducts.types";
import { useCreateProduct } from "../useCreateProduct";

import {
  useProductBrands,
  useProductCategories,
  useProductCollections,
} from "../useProductOrganization";

import { VariantImageUpload } from "./VariantImageUpload";
import { ProductVariantForm } from "./ProductVariantForm";

type FormErrors = {
  name?: string;
  slug?: string;
  categoryId?: string;
  variant?: Record<number, Record<string, string>>;
  general?: string;
};

type ProductFormSubmitEvent = Parameters<
  NonNullable<ComponentProps<"form">["onSubmit"]>
>[0];

export function ProductForm() {
  const [values, setValues] = useState<ProductFormValues>(
    defaultProductFormValues,
  );
  const [errors, setErrors] = useState<FormErrors>({});
  const [skuAutoGenerated, setSkuAutoGenerated] = useState(true);

  const createProduct = useCreateProduct();

  const brandsQuery = useProductBrands();
  const categoriesQuery = useProductCategories();
  const collectionsQuery = useProductCollections();

  // --------------------------------------------------------------------------
  // Helpers
  // --------------------------------------------------------------------------

  const generateSlug = (value: string): string =>
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");

  const isValidNumber = (value: string): boolean => {
    if (!value.trim()) return false;
    const num = Number(value);
    return Number.isFinite(num) && !Number.isNaN(num);
  };

  const validateOptionalDimension = (
    value: string,
    label: string,
    errors: Record<string, string>,
  ) => {
    if (!value.trim()) return;
    if (!isValidNumber(value) || Number(value) < 0) {
      errors[label.toLowerCase()] = `${label} must be 0 or greater.`;
    }
  };

  // --------------------------------------------------------------------------
  // Field updates
  // --------------------------------------------------------------------------

  const updateField = (field: keyof ProductFormValues, value: string) => {
    setValues((current) => ({ ...current, [field]: value }));
    setErrors((current) => ({ ...current, [field]: undefined }));
  };

  const handleNameChange = (name: string) => {
    setValues((current) => {
      const firstVariant = current.variants[0];
      const generatedSku = generateSkuFromName(name);
      const shouldUpdateSku = skuAutoGenerated || !firstVariant?.sku.trim();

      return {
        ...current,
        name,
        slug: current.slug || generateSlug(name),
        variants: [
          {
            ...firstVariant,
            sku: shouldUpdateSku ? generatedSku : firstVariant.sku,
          },
          ...current.variants.slice(1),
        ],
      };
    });
    setErrors((current) => ({ ...current, name: undefined }));
  };

  // --------------------------------------------------------------------------
  // Variant management
  // --------------------------------------------------------------------------

  const addVariant = () => {
    setValues((current) => ({
      ...current,
      variants: [
        ...current.variants,
        {
          sku: "",
          color: "",
          size: "",
          price: "",
          compareAtPrice: "",
          stock: "",
          weight: "",
          actualWeight: "",
          length: "",
          width: "",
          height: "",
          fulfillmentType: "LOCAL",
          shippingType: "LOCAL",
          isActive: true,
          imageIndexes: [], // 👈 new variant gets no images initially
        },
      ],
    }));
  };

  const removeVariant = (index: number) => {
    setValues((current) => ({
      ...current,
      variants: current.variants.filter((_, i) => i !== index),
    }));
  };

  const updateVariant = (index: number, variant: ProductVariantFormValues) => {
    setValues((current) => {
      const newVariants = [...current.variants];
      newVariants[index] = variant;
      return { ...current, variants: newVariants };
    });
    setErrors((current) => ({
      ...current,
      variant: current.variant
        ? (() => {
            const variant = { ...current.variant };
            delete variant[index];
            return variant;
          })()
        : undefined,
    }));
  };

  // --------------------------------------------------------------------------
  // Image management – auto‑assign all images to first variant
  // --------------------------------------------------------------------------

  const handleImagesChange = (newImages: File[]) => {
    setValues((current) => {
      const allIndexes = newImages.map((_, i) => i);
      const updatedVariants = current.variants.map((v, i) => ({
        ...v,
        imageIndexes: i === 0 ? allIndexes : [],
      }));
      return {
        ...current,
        images: newImages,
        variants: updatedVariants,
      };
    });
  };

  // --------------------------------------------------------------------------
  // Validation
  // --------------------------------------------------------------------------

  const validate = (): boolean => {
    const nextErrors: FormErrors = {};

    // Basic fields
    if (!values.name.trim()) {
      nextErrors.name = "Product name is required.";
    } else if (values.name.trim().length < 2) {
      nextErrors.name = "Product name must be at least 2 characters.";
    } else if (values.name.trim().length > 150) {
      nextErrors.name = "Product name cannot exceed 150 characters.";
    }

    if (!values.slug.trim()) {
      nextErrors.slug = "Product slug is required.";
    } else if (values.slug.trim().length < 2) {
      nextErrors.slug = "Product slug must be at least 2 characters.";
    }

    if (!values.categoryId) {
      nextErrors.categoryId = "Please select a category.";
    }

    // Variants
    const variantErrors: Record<number, Record<string, string>> = {};
    let hasVariantError = false;

    values.variants.forEach((variant, index) => {
      const err: Record<string, string> = {};

      if (variant.price.trim() === "") {
        err.price = "Selling price is required.";
      } else if (!isValidNumber(variant.price)) {
        err.price = "Enter a valid selling price.";
      } else if (Number(variant.price) < 0) {
        err.price = "Price cannot be negative.";
      }

      if (variant.weight.trim() === "") {
        err.weight = "Weight is required.";
      } else if (!isValidNumber(variant.weight)) {
        err.weight = "Enter a valid weight.";
      } else if (Number(variant.weight) < 0) {
        err.weight = "Weight cannot be negative.";
      }

      if (variant.actualWeight.trim() === "") {
        err.actualWeight = "Actual weight is required.";
      } else if (!isValidNumber(variant.actualWeight)) {
        err.actualWeight = "Enter a valid actual weight.";
      } else if (Number(variant.actualWeight) < 0) {
        err.actualWeight = "Actual weight cannot be negative.";
      }

      if (
        variant.compareAtPrice.trim() &&
        (!isValidNumber(variant.compareAtPrice) ||
          Number(variant.compareAtPrice) < 0)
      ) {
        err.compareAtPrice = "Enter a valid compare-at price.";
      }

      if (
        variant.stock.trim() &&
        (!isValidNumber(variant.stock) ||
          !Number.isInteger(Number(variant.stock)) ||
          Number(variant.stock) < 0)
      ) {
        err.stock = "Stock must be a whole number of 0 or greater.";
      }

      validateOptionalDimension(variant.length, "Length", err);
      validateOptionalDimension(variant.width, "Width", err);
      validateOptionalDimension(variant.height, "Height", err);

      if (Object.keys(err).length > 0) {
        variantErrors[index] = err;
        hasVariantError = true;
      }
    });

    if (hasVariantError) {
      nextErrors.variant = variantErrors;
    }

    if (values.variants.length === 0) {
      nextErrors.general = "At least one product variant is required.";
    }

    setErrors(nextErrors);
    return Object.keys(nextErrors).length === 0;
  };

  // --------------------------------------------------------------------------
  // Submit
  // --------------------------------------------------------------------------

  const handleSubmit = async (event: ProductFormSubmitEvent) => {
    event.preventDefault();

    if (!validate()) {
      window.scrollTo({ top: 0, behavior: "smooth" });
      return;
    }

    const product = toCreateProductInput(values);

    await createProduct.mutateAsync({
      product,
      images: values.images,
    });

    // Reset form
    setValues(defaultProductFormValues);
    setErrors({});
    setSkuAutoGenerated(true);
  };

  // --------------------------------------------------------------------------
  // Render
  // --------------------------------------------------------------------------

  return (
    <form onSubmit={handleSubmit} noValidate className="space-y-6">
      {/* ------------------------------------------------------------------ */}
      {/* BASIC INFORMATION                                                  */}
      {/* ------------------------------------------------------------------ */}

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
        <div className="border-b border-slate-200 px-6 py-5">
          <h2 className="text-base font-semibold text-slate-900">
            Basic information
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            Give your product a name and description.
          </p>
        </div>

        <div className="grid gap-6 p-6">
          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Product name
              <span className="ml-1 text-red-500">*</span>
            </label>
            <input
              type="text"
              value={values.name}
              onChange={(e) => handleNameChange(e.target.value)}
              placeholder="e.g. Nike Air Max 270"
              className={`w-full rounded-xl border bg-white px-4 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-900 focus:ring-1 focus:ring-slate-900 ${
                errors.name ? "border-red-400" : "border-slate-300"
              }`}
            />
            {errors.name ? (
              <p className="mt-1.5 text-xs text-red-600">{errors.name}</p>
            ) : (
              <p className="mt-1.5 text-xs text-slate-400">
                This is the name customers will see.
              </p>
            )}
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Slug
              <span className="ml-1 text-red-500">*</span>
            </label>
            <input
              type="text"
              value={values.slug}
              onChange={(e) =>
                updateField(
                  "slug",
                  e.target.value.toLowerCase().replace(/\s+/g, "-"),
                )
              }
              placeholder="nike-air-max-270"
              className={`w-full rounded-xl border bg-white px-4 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-900 focus:ring-1 focus:ring-slate-900 ${
                errors.slug ? "border-red-400" : "border-slate-300"
              }`}
            />
            {errors.slug ? (
              <p className="mt-1.5 text-xs text-red-600">{errors.slug}</p>
            ) : (
              <p className="mt-1.5 text-xs text-slate-400">
                Used in the product URL.
              </p>
            )}
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Description
            </label>
            <textarea
              rows={5}
              value={values.description}
              onChange={(e) => updateField("description", e.target.value)}
              placeholder="Describe the product, its features and anything customers should know."
              className="w-full resize-y rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-slate-900 focus:ring-1 focus:ring-slate-900"
            />
            <p className="mt-1.5 text-xs text-slate-400">Optional.</p>
          </div>
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* ORGANIZATION                                                       */}
      {/* ------------------------------------------------------------------ */}

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
        <div className="border-b border-slate-200 px-6 py-5">
          <h2 className="text-base font-semibold text-slate-900">
            Organization
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            Organize this product within your catalog.
          </p>
        </div>

        <div className="grid gap-5 p-6 md:grid-cols-3">
          <Select
            label="Category"
            required
            value={values.categoryId}
            onChange={(value) => updateField("categoryId", value)}
            options={categoriesQuery.data ?? []}
            loading={categoriesQuery.isLoading}
            error={categoriesQuery.isError}
            errorMessage={errors.categoryId}
          />

          <Select
            label="Brand"
            value={values.brandId}
            onChange={(value) => updateField("brandId", value)}
            options={brandsQuery.data ?? []}
            loading={brandsQuery.isLoading}
            error={brandsQuery.isError}
          />

          <Select
            label="Collection"
            value={values.collectionId}
            onChange={(value) => updateField("collectionId", value)}
            options={collectionsQuery.data ?? []}
            loading={collectionsQuery.isLoading}
            error={collectionsQuery.isError}
          />
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* VARIANTS                                                           */}
      {/* ------------------------------------------------------------------ */}

      {values.variants.map((variant, index) => (
        <ProductVariantForm
          key={index}
          variant={variant}
          onChange={(updated) => updateVariant(index, updated)}
          errors={errors.variant?.[index]}
          onSkuChange={() => setSkuAutoGenerated(false)}
          onRemove={
            values.variants.length > 1 ? () => removeVariant(index) : undefined
          }
          allImages={values.images} // 👈 pass global images for image selection
        />
      ))}

      <button
        type="button"
        onClick={addVariant}
        className="rounded-lg border border-dashed border-slate-300 px-4 py-2 text-sm text-slate-600 hover:border-slate-500 hover:text-slate-900"
      >
        + Add another variant
      </button>

      {/* ------------------------------------------------------------------ */}
      {/* IMAGES                                                             */}
      {/* ------------------------------------------------------------------ */}

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
        <div className="border-b border-slate-200 px-6 py-5">
          <h2 className="text-base font-semibold text-slate-900">
            Product images
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            Upload up to 5 images. The first image will be used as the primary
            image.
          </p>
        </div>

        <div className="p-6">
          <VariantImageUpload
            files={values.images}
            onChange={handleImagesChange} // 👈 auto‑assign on upload
          />
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* VISIBILITY                                                         */}
      {/* ------------------------------------------------------------------ */}

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
        <div className="border-b border-slate-200 px-6 py-5">
          <h2 className="text-base font-semibold text-slate-900">
            Store visibility
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            Control how this product is presented in the store.
          </p>
        </div>

        <div className="divide-y divide-slate-100">
          <VisibilityRow
            label="Featured product"
            description="Highlight this product in featured sections."
            checked={values.isFeatured}
            onChange={(checked) =>
              setValues((current) => ({ ...current, isFeatured: checked }))
            }
          />

          <VisibilityRow
            label="New arrival"
            description="Mark this product as a new arrival."
            checked={values.isNew}
            onChange={(checked) =>
              setValues((current) => ({ ...current, isNew: checked }))
            }
          />

          <VisibilityRow
            label="Best seller"
            description="Mark this product as a best seller."
            checked={values.isBestSeller}
            onChange={(checked) =>
              setValues((current) => ({ ...current, isBestSeller: checked }))
            }
          />
        </div>

        <div className="border-t border-slate-200 bg-slate-50 px-6 py-5">
          <label className="mb-2 block text-sm font-medium text-slate-700">
            Initial status
          </label>
          <select
            value={values.status}
            onChange={(e) =>
              setValues((current) => ({
                ...current,
                status: e.target.value as ProductFormValues["status"],
              }))
            }
            className="w-full max-w-sm rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none focus:border-slate-900 focus:ring-1 focus:ring-slate-900"
          >
            <option value="DRAFT">Draft</option>
            <option value="ACTIVE">Active</option>
          </select>
          <p className="mt-1.5 text-xs text-slate-400">
            Draft products can be completed before being made available to
            customers.
          </p>
        </div>
      </section>

      {/* ------------------------------------------------------------------ */}
      {/* ERRORS                                                             */}
      {/* ------------------------------------------------------------------ */}

      {errors.general && <ErrorBanner>{errors.general}</ErrorBanner>}

      {createProduct.isError && (
        <ErrorBanner>
          {createProduct.error instanceof Error
            ? createProduct.error.message
            : "Unable to create product. Please check the form and try again."}
        </ErrorBanner>
      )}

      {/* ------------------------------------------------------------------ */}
      {/* ACTIONS                                                            */}
      {/* ------------------------------------------------------------------ */}

      <div className="sticky bottom-0 z-10 -mx-4 border-t border-slate-200 bg-white/95 px-4 py-4 backdrop-blur sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div className="flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="text-xs text-slate-400">
            Fields marked with <span className="mx-1 text-red-500">*</span> are
            required.
          </div>

          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => {
                setValues(defaultProductFormValues);
                setErrors({});
                setSkuAutoGenerated(true);
              }}
              disabled={createProduct.isPending}
              className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-medium text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Reset
            </button>

            <button
              type="submit"
              disabled={createProduct.isPending}
              className="rounded-xl bg-slate-900 px-6 py-3 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {createProduct.isPending
                ? "Creating product..."
                : values.status === "DRAFT"
                  ? "Save product"
                  : "Create product"}
            </button>
          </div>
        </div>
      </div>

      {createProduct.isSuccess && (
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">
          Product created successfully.
        </div>
      )}
    </form>
  );
}

// ----------------------------------------------------------------------------
// Sub‑components (unchanged)
// ----------------------------------------------------------------------------

interface SelectProps {
  label: string;
  required?: boolean;
  value: string;
  options: { id: string; name: string; isActive: boolean }[];
  onChange: (value: string) => void;
  loading?: boolean;
  error?: boolean;
  errorMessage?: string;
}

function Select({
  label,
  required = false,
  value,
  options,
  onChange,
  loading = false,
  error = false,
  errorMessage,
}: SelectProps) {
  return (
    <div>
      <label className="mb-2 block text-sm font-medium text-slate-700">
        {label}
        {required && <span className="ml-1 text-red-500">*</span>}
      </label>

      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        disabled={loading || error}
        className={`w-full rounded-xl border bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-slate-900 focus:ring-1 focus:ring-slate-900 disabled:cursor-not-allowed disabled:bg-slate-50 ${
          errorMessage || error ? "border-red-400" : "border-slate-300"
        }`}
      >
        <option value="">
          {loading
            ? `Loading ${label.toLowerCase()}...`
            : error
              ? `Unable to load ${label.toLowerCase()}`
              : `Select ${label.toLowerCase()}`}
        </option>

        {options
          .filter((item) => item.isActive)
          .map((item) => (
            <option key={item.id} value={item.id}>
              {item.name}
            </option>
          ))}
      </select>

      {errorMessage && (
        <p className="mt-1.5 text-xs text-red-600">{errorMessage}</p>
      )}
    </div>
  );
}

function VisibilityRow({
  label,
  description,
  checked,
  onChange,
}: {
  label: string;
  description: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
}) {
  return (
    <div className="flex items-center justify-between gap-5 px-6 py-5">
      <div>
        <p className="text-sm font-medium text-slate-900">{label}</p>
        <p className="mt-1 text-xs text-slate-500">{description}</p>
      </div>

      <button
        type="button"
        role="switch"
        aria-checked={checked}
        onClick={() => onChange(!checked)}
        className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${
          checked ? "bg-slate-900" : "bg-slate-300"
        }`}
      >
        <span
          className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${
            checked ? "translate-x-6" : "translate-x-1"
          }`}
        />
      </button>
    </div>
  );
}

function ErrorBanner({ children }: { children: ReactNode }) {
  return (
    <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
      {children}
    </div>
  );
}
